services:
  - type: web
    name: permisosadmin
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: FORCE_REBUILD
        value: "true"
